### ISSUE TITLE
Get familiar with pgRouting on Github

### ISSUE THREAD

**Issue by XJTUmg** [XJTUmg/pgrouting#2]
Currently trsp <a target="_blank" href="https://travis-ci.org/pgRouting/pgrouting/jobs/201256181#L799"> compilation</a> has lots of problems:

- Files that start with **/usr/include/postgresql/9.6/server/** are not pgRouting files so they can not be modified.
- Files that start with **home/travis/build/pgRouting/pgrouting/** belong to pgRouting and they can be modified.
- [x] Start on develop branch
- [x] Choose a compilation warning on a file that belongs to pgRouting
- [x] Propose a solution to remove the warning
- [x] Submit a pull request to develop.

**Comment by cvvergara** [comment]
pull request
https://github.com/pgRouting/pgrouting/pull/739
date Feb 28
Was included as part of 2.4.0 release
