### ISSUE TITLE
Improve Proposal

### ISSUE THREAD

**Issue by XJTUmg** [XJTUmg/pgrouting#6]
- [x] write and commit sample sql code for demo slides to repo "ExampleCode".
- [x] find more applications of connected components algorithms.
- [ ] make gantt chart for timeline.
- [x] reconsider timeline, try to make it better.
- [x] complete references.
- [x] recheck code.
- [x] format text with a standard font size.
- [x] remove references, add footnotes.
- [x] remove 'link', add link to the text.

**Comment by cvvergara** [comment]
FYI I think the time line is ok.

**Comment by XJTUmg** [comment]
- [x] enhance timeline to reflect <a target="_blank" href="https://www.google.com/url?q=https://lists.osgeo.org/pipermail/soc/2017-March/003556.html&sa=D&ust=1490333573218000&usg=AFQjCNEpCTJJJwn-3QyIsmkN0yl3YGmJKA"> these </a> needs.
- [x] fix a link error in 'Benefits to Community' ('Read more')

**Comment by XJTUmg** [comment]
- [x] fix grammer mistakes.

**Comment by XJTUmg** [comment]
- [x] add ```cost``` and ```reverse_cost``` parameters to those three proposed functions.
- [x] add new reference (<a target="_blank" href="http://docs.pgrouting.org/2.4/en/sampledata.html"> pgRouting sample data </a>)
- [x] investigate ```pgr_labelGraph```. If it can be replaced with one of those three proposed functions, write about it in proposal.
- [x] add a new line to 'Attention' which has descriptions of the proposed sql queries. (use <a target="_blank" href="http://docs.pgrouting.org/2.4/en/pgRouting-concepts.html#inner-queries"> dijkstra like inner queries </a>).
- [x] analyze pgRouting Sample Data.

**Comment by XJTUmg** [comment]
- [x] review and check any requirement from OSGeo or GSoC.

**Comment by XJTUmg** [comment]
- [x] Add img about pgRouting Sample Data analysis.
